In [2]:
import arablepy
import pandas as pd

client = arablepy.ArableClient()

In [3]:
  #  client.connect(email='lestes@clarku.edu', password='rollinghills88')
#client.connect(email='caylor@ucsb.edu', password='greenresearch11')
client.connect(email='lestes@clarku.edu', password='rollinghills88')

In [4]:
## types of data sets
## we will mostly use "daily"
client.schema(df=True)

                                    0
0                             aux_raw
1                               daily
2                              health
3                              hourly
4            irrigation_runtime_daily
5           irrigation_runtime_hourly
6                        local_hourly
7  location_irrigation_forecast_daily
8                        sentek_daily
9                       sentek_hourly

In [5]:
## columns in "daily" data set
client.schema('daily', df=True)

,column_name,data_type,description
0,cl,real,Chlorophyll Index (unitless index)
1,crop_water_demand,real,Crop water demand (mm/day)
2,device,text,"Arable device ID (e.g., A000176)"
3,dli,real,Daily Light Integral
4,ea,double precision,Actual Water Vapor Pressure (kPa)
5,et,real,Evapotranspiration (ETo) (mm)
6,etc,double precision,Crop Evapotranspiration (mm)
7,kc,double precision,"Crop coefficient, Kc (unitless)"
8,lat,real,Latitude (decimal degree)
9,lfairdelta,real,Leaf to air temperature difference (C)
10,lfw,real,Leaf wetness (hours)
11,location,text,Location ID (24-digit hex)
12,long,real,Longitude (decimal degree)
13,low_quality,boolean,True for Low Data Quality
14,maxt,real,Daily maximum temperature (C)
15,max_tdew,double precision,The maximum dew point temperature (C) over the...
16,maxt_time,timestamp without time zone,The time in local time when a maximum temperat...
17,meant,real,Daily mean temperature (C)
18,mean_tbelow,real,Daily mean leaf/ground temperature (C)
19,min_rh,real,The minimum relative humidity (between 0 and 1...
20,mint,real,Daily minimum temperature (C)
21,mint_time,timestamp without time zone,The time in local time when a minimum temperat...
22,ndvi,real,Normalized Difference Vegetation Index (unitle...
23,prate,real,Precipitation rate (mm/day)
24,precip,real,Precipitation total (mm)
25,precip_hours,real,Number of hours with more than 0.1mm rain per day
26,rh_at_maxt,real,The Relative humidity (between 0 and 1) when a...
27,rh_at_mint,real,The Relative humidity (between 0 and 1) when a...
28,sample_pct,double precision,Aggregation Sample Percent
29,slp,double precision,Sea Level Pressure (kPa)
30,sunshine_duration,double precision,Hours of downwelling shortwave radiation >120 ...
31,swdw,real,"Shortwave downwelling radiation, daily total (..."
32,tdew,double precision,Dew temperature (C)
33,tdew_at_mint,real,The Dew temperature (C) when a minimum tempera...
34,time,timestamp with time zone,Local date
35,vpd,double precision,Vapor Pressure Deficit (kPa)
36,wind_direction,character varying,"Wind direction; N, NNE, NE, etc."
37,wind_heading,real,"Wind heading, degrees"
38,wind_speed,real,"Wind speed, stored as m/s"
39,wind_speed_max,real,"Max wind speed, stored as m/s"
40,wind_speed_min,real,"Min wind speed, stored as m/s"

In [4]:
 a =   client.data('daily', devices='A000680', start_time='2020-01-01T00:00:00Z', end_time='2020-07-07T00:00:00Z', df=False)
print(a)

Empty DataFrame
Columns: []
Index: []

In [6]:
from datetime import date
today = date.today()
d1 = today.strftime("%Y-%m-%d")
print("today's date ", d1)

today's date  2021-04-20

In [9]:
df = client.data('daily', devices= ['A000680'], start_time='2017-01-01', end_time= d1)
print(df)

     precip_hours  mean_tbelow gdd_source      lat  crop_water_demand  \
0             NaN          NaN       None  42.1218                NaN
1             NaN          NaN       None  42.1218                NaN
2             NaN          NaN       None  42.1218                NaN
3             NaN          NaN       None  42.1218                NaN
4             NaN          NaN       None  42.1218                NaN
..            ...          ...        ...      ...                ...
270           0.0         22.2       None  42.1218               -0.9
271           0.0         24.1       None  42.1218               -1.0
272           0.0         24.0       None  42.1220               -0.6
273           6.0         24.1       None  42.1218                6.7
274           1.0         21.1       None  42.1218                NaN

                maxt_time  rh_at_maxt wind_speed_min  mint    ea  ...  \
0                    None         NaN           None  15.1   NaN  ...
1                    None         NaN           None  14.5   NaN  ...
2                    None         NaN           None  11.5   NaN  ...
3                    None         NaN           None  10.0   NaN  ...
4                    None         NaN           None  12.7   NaN  ...
..                    ...         ...            ...   ...   ...  ...
270  2020-09-07T15:54:34Z        0.55           None  10.3  1.43  ...
271  2020-09-08T15:19:11Z        0.52           None  11.5  1.68  ...
272  2020-09-09T12:48:38Z        0.51           None  12.3  1.73  ...
273  2020-09-10T15:29:03Z        0.83           None  13.8  1.47  ...
274  2020-09-11T00:00:46Z        0.93           None   9.1  2.15  ...

    wind_speed   device  meant sunshine_duration  sample_pct wind_speed_max  \
0         None  A000680   19.6               NaN         NaN           None
1         None  A000680   17.8               NaN         NaN           None
2         None  A000680   15.2               NaN         NaN           None
3         None  A000680   15.2               NaN         NaN           None
4         None  A000680   16.5               NaN         NaN           None
..         ...      ...    ...               ...         ...            ...
270       None  A000680   15.9              10.0        1.00           None
271       None  A000680   18.7               9.4        1.00           None
272       None  A000680   19.1               8.8        1.00           None
273       None  A000680   19.4               6.9        1.00           None
274       None  A000680   16.0               0.2        0.41           None

                     location  min_rh  swdw  lfw
0    5b1aaa3af2a0ff00019bedea     NaN  25.9  NaN
1    5b1aaa3af2a0ff00019bedea     NaN  18.2  NaN
2    5b1aaa3af2a0ff00019bedea     NaN  23.6  NaN
3    5b1aaa3af2a0ff00019bedea     NaN  29.6  NaN
4    5b1aaa3af2a0ff00019bedea     NaN   9.7  NaN
..                        ...     ...   ...  ...
270  5d08fd61c74fb853ad5853ac    0.53  16.7  0.0
271  5d08fd61c74fb853ad5853ac    0.49  15.8  2.0
272  5d08fd61c74fb853ad5853ac    0.45  12.7  5.0
273  5d08fd61c74fb853ad5853ac    0.81   9.0  4.0
274  5d08fd61c74fb853ad5853ac    0.89   2.2  2.0

[275 rows x 45 columns]

In [11]:
## save data frame to csv
fname = "./" + "A000680_daily.csv"
df.to_csv(fname)

In [12]:
from datetime import date
today = date.today()
d1 = today.strftime("%Y-%m-%d")
print(d1)


devices=['A000667', 'A000680', 'A000671']   # new


for device in devices: 
    device_list = [device]
    print(device)
    df = client.data('hourly', devices=device_list,start_time='2017-01-01', end_time= d1)
    fname = './' + device + '_hourly.csv'
    df.to_csv(fname)
    df = client.data('daily', devices=device_list ,start_time='2017-10-01', end_time=d1)
    fname = './' + device + '_daily.csv'
    df.to_csv(fname)

df

2021-04-20
A000667
A000680
A000671

,dli,wind_direction,vpd,ndvi,mean_tbelow,lat,precip_hours,lfairdelta,kc,sample_pct,...,wind_speed_min,etc,min_rh,gdd_cumulative_source,cl,et,precip,wind_heading,wind_speed,mint
0,35.07,None,NaN,0.16,NaN,42.1207,NaN,7.7,0.07,NaN,...,None,0.3,NaN,None,0.33,5.2,NaN,None,None,15.0
1,24.51,None,NaN,0.16,NaN,42.1207,NaN,5.7,0.06,NaN,...,None,0.2,NaN,None,0.33,3.7,0.0,None,None,14.4
2,31.44,None,NaN,0.16,NaN,42.1207,NaN,10.8,0.07,NaN,...,None,0.3,NaN,None,0.34,4.1,0.0,None,None,11.4
3,39.21,None,NaN,0.16,NaN,42.1207,NaN,9.3,0.07,NaN,...,None,0.3,NaN,None,0.34,5.0,1.3,None,None,9.9
4,13.74,None,NaN,0.17,NaN,42.1207,NaN,3.9,0.08,NaN,...,None,0.1,NaN,None,0.36,1.1,0.3,None,None,12.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,17.19,None,0.5,0.58,21.9,42.1230,0.0,5.9,0.67,1.0,...,None,1.6,0.51,None,3.92,2.4,0.0,None,None,15.1
273,16.36,None,0.6,0.57,23.6,42.1230,0.0,5.9,0.66,1.0,...,None,1.6,0.48,None,3.79,2.4,0.0,None,None,15.8
274,11.90,None,0.6,0.55,23.6,42.1230,0.0,5.6,0.64,1.0,...,None,1.2,0.44,None,3.71,1.9,0.0,None,None,16.3
275,7.08,None,0.1,0.55,23.7,42.1230,5.0,4.0,0.63,1.0,...,None,0.5,0.81,None,3.80,0.9,5.9,None,None,18.1
276,1.21,None,0.6,-0.29,23.9,42.1230,7.0,4.9,0.00,0.8,...,None,0.0,0.23,None,-0.29,0.8,9.8,None,None,15.3

                                    0
0                             aux_raw
1                               daily
2                              health
3                              hourly
4            irrigation_runtime_daily
5           irrigation_runtime_hourly
6                        local_hourly
7  location_irrigation_forecast_daily
8                        sentek_daily
9                       sentek_hourly