In [2]:
import arablepy
import pandas as pd

client = arablepy.ArableClient()

In [3]:
  #  client.connect(email='lestes@clarku.edu', password='rollinghills88')
#client.connect(email='caylor@ucsb.edu', password='greenresearch11')
client.connect(email='lestes@clarku.edu', password='rollinghills88')

In [4]:
## types of data sets
## we will mostly use "daily"
client.schema(df=True)

                                    0
0                             aux_raw
1                               daily
2                              health
3                              hourly
4            irrigation_runtime_daily
5           irrigation_runtime_hourly
6                        local_hourly
7  location_irrigation_forecast_daily
8                        sentek_daily
9                       sentek_hourly

In [6]:
## columns in "daily" data set
client.schema('hourly', df=True)

,column_name,data_type,description
0,b1dw,real,Spectrometer data bands 1-7 downwelling (W/m^2)
1,b1uw,real,Spectrometer data bands 1-7 upwelling (W/m^2)
2,b2dw,real,Spectrometer data bands 1-7 downwelling (W/m^2)
3,b2uw,real,Spectrometer data bands 1-7 upwelling (W/m^2)
4,b3dw,real,Spectrometer data bands 1-7 downwelling (W/m^2)
5,b3uw,real,Spectrometer data bands 1-7 upwelling (W/m^2)
6,b4dw,real,Spectrometer data bands 1-7 downwelling (W/m^2)
7,b4uw,real,Spectrometer data bands 1-7 upwelling (W/m^2)
8,b5dw,real,Spectrometer data bands 1-7 downwelling (W/m^2)
9,b5uw,real,Spectrometer data bands 1-7 upwelling (W/m^2)
10,b6dw,real,Spectrometer data bands 1-7 downwelling (W/m^2)
11,b6uw,real,Spectrometer data bands 1-7 upwelling (W/m^2)
12,b7dw,real,Spectrometer data bands 1-7 downwelling (W/m^2)
13,b7uw,real,Spectrometer data bands 1-7 upwelling (W/m^2)
14,device,text,"Arable device ID (e.g., A000176)"
15,ea,double precision,Actual Water Vapor Pressure (kPa)
16,et,real,Evapotranspiration (ETo) (mm)
17,etc,real,Crop Evapotranspiration (mm)
18,et_version,character varying,None
19,lat,real,Latitude (decimal degree)
20,lfw,real,Leaf wetness (min)
21,location,text,Location ID (24-digit hex)
22,long,real,Longitude (decimal degree)
23,low_quality,boolean,True for Low Data Quality
24,lwdw,real,"Longwave downwelling, hourly mean (W/m^2)"
25,lwuw,real,"Longwave upwelling, hourly mean (W/m^2)"
26,maxt,real,The maximum air temperature experienced during...
27,max_tdew,double precision,The maximum dew point temperature (C) in the hour
28,min_rh,real,The minimum relative humidity (between 0 and 1...
29,mint,real,The minimum air temperature experienced during...
30,p,real,Pressure (kPa)
31,pardw,real,Photosynthetically Active Radiation downwellin...
32,paruw,real,Photosynthetically Active Radiation upwelling ...
33,prate,real,Precipitation rate (mm/h)
34,precip,real,Precipitation total (mm)
35,rh,real,Relative humidity (between 0 and 1)
36,rh_at_maxt,real,The Relative humidity (between 0 and 1) when a...
37,sample_pct,double precision,Aggregation Sample Percent
38,slp,double precision,Sea Level Pressure (kPa)
39,swdw,real,"Short wave downwelling, hourly mean (W/m^2)"
40,swuw,real,"Short wave upwelling, hourly mean (W/m^2)"
41,tabove,real,Sky temperature (C)
42,tair,real,Air temperature (C)
43,tbelow,real,Leaf/ground temperature (C)
44,tdew,real,Dew temperature (C)
45,time,timestamp with time zone,UTC time
46,vpd,double precision,Vapor Pressure Deficit (kPa)
47,wind_direction,character varying,"Wind direction; N, NNE, NE, etc."
48,wind_heading,real,"Wind heading, degrees"
49,wind_speed,real,"Wind speed, stored as m/s"
50,wind_speed_max,real,"Max wind speed, stored as m/s"
51,wind_speed_min,real,"Min wind speed, stored as m/s"

In [7]:
#  a =   client.data('daily', devices='A000680', start_time='2020-01-01', end_time='2020-07-07T00:00:00Z', df=False)
# print(a)

Empty DataFrame
Columns: []
Index: []

In [8]:
from datetime import date
today = date.today()
d1 = today.strftime("%Y-%m-%d")
print("today's date ", d1)

today's date  2021-04-20

In [9]:
df = client.data('daily', devices= ['A000680'], start_time='2017-01-01', end_time= d1)
print(df)

       ea  crop_water_demand  sunshine_duration                  time    dli  \
0     NaN                NaN                NaN  2018-06-09T00:00:00Z  34.82
1     NaN                NaN                NaN  2018-06-10T00:00:00Z  24.48
2     NaN                NaN                NaN  2018-06-11T00:00:00Z  31.68
3     NaN                NaN                NaN  2018-06-12T00:00:00Z  39.85
4     NaN                NaN                NaN  2018-06-13T00:00:00Z  13.04
..    ...                ...                ...                   ...    ...
270  1.43               -0.9               10.0  2020-09-07T00:00:00Z  20.80
271  1.68               -1.0                9.4  2020-09-08T00:00:00Z  19.62
272  1.73               -0.6                8.8  2020-09-09T00:00:00Z  15.75
273  1.47                6.7                6.9  2020-09-10T00:00:00Z  11.22
274  2.15                NaN                0.2  2020-09-11T00:00:00Z   2.78

     prate wind_speed    slp   et  vpd  ...  lfairdelta  rh_at_maxt  \
0      NaN       None  101.8  5.2  NaN  ...         8.5         NaN
1      NaN       None  101.7  3.8  NaN  ...         6.0         NaN
2      NaN       None  101.7  4.3  NaN  ...        11.0         NaN
3      0.0       None  102.1  5.2  NaN  ...        10.0         NaN
4      0.2       None  101.4  1.1  NaN  ...         4.5         NaN
..     ...        ...    ...  ...  ...  ...         ...         ...
270    0.0       None  102.0  2.0  0.5  ...         7.4        0.55
271    0.0       None  102.2  2.1  0.6  ...         6.3        0.52
272    0.0       None  102.6  1.8  0.6  ...         6.8        0.51
273    6.8       None  102.4  1.0  0.2  ...         5.6        0.83
274    1.2       None  102.1  0.1  0.2  ...         NaN        0.93

     wind_speed_max  lfw  wind_direction  mint precip     long  \
0              None  NaN            None  15.1    NaN -71.8065
1              None  NaN            None  14.5    NaN -71.8065
2              None  NaN            None  11.5    NaN -71.8065
3              None  NaN            None  10.0    0.0 -71.8065
4              None  NaN            None  12.7    0.2 -71.8065
..              ...  ...             ...   ...    ...      ...
270            None  0.0            None  10.3    0.0 -71.8065
271            None  2.0            None  11.5    0.0 -71.8065
272            None  5.0            None  12.3    0.0 -71.8065
273            None  4.0            None  13.8    6.8 -71.8065
274            None  2.0            None   9.1    1.2 -71.8065

    gdd_cumulative_source  tdew_at_mint
0                    None           NaN
1                    None           NaN
2                    None           NaN
3                    None           NaN
4                    None           NaN
..                    ...           ...
270                  None          14.8
271                  None          15.5
272                  None          17.2
273                  None          17.1
274                  None          15.6

[275 rows x 45 columns]

In [10]:
## save data frame to csv
fname = "./" + "A000680_daily.csv"
df.to_csv(fname)

In [11]:
from datetime import date
today = date.today()
d1 = today.strftime("%Y-%m-%d")
print(d1)


devices=['A000667', 'A000680', 'A000671']   # new


for device in devices: 
    device_list = [device]
    print(device)
    df = client.data('hourly', devices=device_list,start_time='2017-01-01', end_time= d1)
    fname = './' + device + '_hourly.csv'
    df.to_csv(fname)
    df = client.data('daily', devices=device_list ,start_time='2017-10-01', end_time=d1)
    fname = './' + device + '_daily.csv'
    df.to_csv(fname)

df

2021-04-20
A000667
A000680
A000671

,meant,ndvi,precip,lfairdelta,mint_time,wind_speed_max,mean_tbelow,ea,gdd_cumulative_source,kc,...,maxt_time,tdew_at_mint,wind_heading,lfw,cl,device,low_quality,tdew,gdd_source,dli
0,19.7,0.16,NaN,7.7,None,None,NaN,NaN,None,0.07,...,None,NaN,None,NaN,0.33,A000671,None,NaN,None,35.07
1,17.6,0.16,0.0,5.7,None,None,NaN,NaN,None,0.06,...,None,NaN,None,NaN,0.33,A000671,None,NaN,None,24.51
2,15.0,0.16,0.0,10.8,None,None,NaN,NaN,None,0.07,...,None,NaN,None,NaN,0.34,A000671,None,NaN,None,31.44
3,15.1,0.16,1.3,9.3,None,None,NaN,NaN,None,0.07,...,None,NaN,None,NaN,0.34,A000671,None,NaN,None,39.21
4,16.5,0.17,0.3,3.9,None,None,NaN,NaN,None,0.08,...,None,NaN,None,NaN,0.36,A000671,None,NaN,None,13.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,18.7,0.58,0.0,5.9,2020-09-07T05:48:28Z,None,21.9,1.87,None,0.67,...,2020-09-07T16:10:19Z,15.6,None,10.0,3.92,A000671,False,15.4,None,17.19
273,20.7,0.57,0.0,5.9,2020-09-08T06:53:12Z,None,23.6,1.86,None,0.66,...,2020-09-08T16:29:57Z,17.1,None,12.0,3.79,A000671,False,17.8,None,16.36
274,20.4,0.55,0.0,5.6,2020-09-09T01:56:47Z,None,23.6,2.05,None,0.64,...,2020-09-09T13:08:55Z,18.5,None,10.0,3.71,A000671,False,17.6,None,11.90
275,21.5,0.55,5.9,4.0,2020-09-10T02:36:28Z,None,23.7,2.07,None,0.63,...,2020-09-10T16:29:03Z,18.6,None,22.0,3.80,A000671,False,21.5,None,7.08
276,21.4,-0.29,9.8,4.9,2020-09-11T11:32:49Z,None,23.9,2.59,None,0.00,...,2020-09-11T13:53:17Z,17.4,None,17.0,-0.29,A000671,False,18.8,None,1.21

                                    0
0                             aux_raw
1                               daily
2                              health
3                              hourly
4            irrigation_runtime_daily
5           irrigation_runtime_hourly
6                        local_hourly
7  location_irrigation_forecast_daily
8                        sentek_daily
9                       sentek_hourly